/**
 * Pathways v1 catalog (PTH-1).
 *
 * Single source of truth for all 9 Pathways at launch.
 *  - One Pathway is `comingSoon: false` (Complete IQ Foundation).
 *  - The other eight ship as premium "coming soon" cards with real
 *    identity copy so the catalog feels like a real product, not a
 *    one-track demo.
 *
 * Scenario IDs reference rows that already exist in `Scenario` —
 * Pathways never duplicate scenario content, only sequence it.
 *
 * Mirrors §5 + §6 of `docs/courtiq-pathways-product-plan.md`.
 */

import type { PathwayConfig } from './types'

const BDW_IDS = ['BDW-01', 'BDW-02', 'BDW-03', 'BDW-04', 'BDW-05'] as const
const ESC_IDS = ['ESC-01', 'ESC-02', 'ESC-03', 'ESC-04', 'ESC-05'] as const
const AOR_IDS = ['AOR-01', 'AOR-02', 'AOR-03', 'AOR-04', 'AOR-05'] as const
const SKR_IDS = ['SKR-01', 'SKR-02', 'SKR-03', 'SKR-04', 'SKR-05'] as const
const DROP_IDS = [
  'DROP-01',
  'DROP-01-MIRROR',
  'DROP-02',
  'DROP-02-MIRROR',
  'DROP-03',
  'DROP-03-MIRROR',
] as const

/**
 * Foundation chapter mastery thresholds. Mirror §6 of the planning doc:
 * a chapter is mastered when ≥ 4 of 5 best answers are present *and* the
 * chapter's decoder rolling accuracy is ≥ 0.80 across ≥ 5 attempts.
 */
const CHAPTER_PASS: PathwayConfig['chapters'][number]['passCriteria'] = {
  minBest: 3,
  minDecoderAccuracy: 0.6,
  minDecoderAttempts: 3,
}

const CHAPTER_MASTERY: PathwayConfig['chapters'][number]['masteryCriteria'] = {
  minBest: 4,
  minDecoderAccuracy: 0.8,
  minDecoderAttempts: 5,
}

const FOUNDATION: PathwayConfig = {
  slug: 'complete-iq-foundation',
  title: 'Complete IQ Foundation',
  subtitle: 'Build your basketball brain from the ground up.',
  description:
    'Learn to read denial, move when defenders look away, beat closeouts, and punish help rotations. Five chapters, twenty reps, and the four reads every position needs.',
  accentToken: 'brand',
  decoderTags: ['BACKDOOR_WINDOW', 'EMPTY_SPACE_CUT', 'ADVANTAGE_OR_RESET', 'SKIP_THE_ROTATION'],
  estimatedMinutes: 45,
  recommendedFor: ['ball-watcher', 'cutter', 'connector', 'attacker'],
  targetArchetype: 'cutter',
  comingSoon: false,
  basketballProblem:
    'Player watches the ball, freezes on the catch, and reacts to defender cues a half-step late.',
  difficultyRange: [1, 3],
  unlockCriteria: { alwaysAvailable: true },
  passCriteria: { minBest: 16, minDecoderAccuracy: 0.7 },
  parentSummary:
    'Foundational five-chapter track that teaches a player to recognize four universal off-ball / catch-decide cues: backdoor windows, empty-space reads, advantage-vs-reset closeouts, and help-rotation skips.',
  coachSummary:
    'Built on 20 youth basketball scenarios, each authored against a single best-read with feedback for every option. Master this and your player will recognize the four reads that decide possessions before the catch.',
  chapters: [
    {
      slug: 'read-the-denial',
      order: 1,
      title: 'Read the Denial',
      subtitle: 'When the defender blocks the pass, the basket is open.',
      basketballCue:
        "Defender's hand or foot in the passing lane (chest between ball and receiver).",
      decoderTag: 'BACKDOOR_WINDOW',
      decoderTags: ['BACKDOOR_WINDOW'],
      goal: 'Learn when your defender blocks the passing lane and how to punish it by cutting behind.',
      parentSummary:
        'Player can recognize a denied passing lane and counters with a back-cut rather than holding the spot. Foundation read for off-ball offense.',
      coachSummary:
        'Player will recognize a denied passing lane (hand/foot in lane, chest blocking line) and counter with a back-cut to the rim.',
      passCriteria: CHAPTER_PASS,
      masteryCriteria: CHAPTER_MASTERY,
      skillNodes: [
        {
          slug: 'learn-the-cue',
          order: 1,
          title: 'Learn the Cue',
          subtitle: 'Read the lesson, then take one easy rep.',
          kind: 'learn-cue',
          trainingMode: 'learn-the-cue',
          academyLessonSlug: 'backdoor-window',
          scenarioIds: ['BDW-01'],
        },
        {
          slug: 'first-reps',
          order: 2,
          title: 'First Reps',
          subtitle: 'Two clean denials.',
          kind: 'scenario-set',
          trainingMode: 'freeze-frame-read',
          scenarioIds: ['BDW-01', 'BDW-02'],
          prerequisiteNodeSlugs: ['learn-the-cue'],
        },
        {
          slug: 'disguised-denials',
          order: 3,
          title: 'Disguised Denials',
          subtitle: 'Corner and slot variants.',
          kind: 'scenario-set',
          trainingMode: 'freeze-frame-read',
          scenarioIds: ['BDW-03', 'BDW-04'],
          prerequisiteNodeSlugs: ['first-reps'],
        },
        {
          slug: 'timing-test',
          order: 4,
          title: 'Timing Test',
          subtitle: 'Cut on the air pass.',
          kind: 'scenario-set',
          trainingMode: 'freeze-frame-read',
          scenarioIds: ['BDW-05'],
          prerequisiteNodeSlugs: ['disguised-denials'],
        },
      ],
      bossChallenge: {
        slug: 'denial-reader',
        title: 'Boss — Denial Reader',
        subtitle: '5 reps. No hints. 80% to pass.',
        scenarioIds: [...BDW_IDS],
        passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
        hideDecoderPill: true,
      },
    },
    {
      slug: 'move-when-eyes-leave',
      order: 2,
      title: 'Move When Eyes Leave',
      subtitle: 'When the defender looks at the ball, you go.',
      basketballCue:
        "Defender's eyes / hips / shoulders rotate toward the ball; nearby floor space is empty.",
      decoderTag: 'EMPTY_SPACE_CUT',
      decoderTags: ['EMPTY_SPACE_CUT'],
      goal: 'Learn to cut, drift, or replace when your defender turns toward the ball or to help.',
      parentSummary:
        "Player anticipates help defense by reading the defender's eyes/hips and relocates *before* the rotation completes. The off-ball habit that separates effective wings from bystanders.",
      coachSummary:
        "Player will move on the help turn instead of after it, exploiting the half-second gap before the defender's body follows their eyes.",
      passCriteria: CHAPTER_PASS,
      masteryCriteria: CHAPTER_MASTERY,
      skillNodes: [
        {
          slug: 'learn-the-cue',
          order: 1,
          title: 'Learn the Cue',
          subtitle: 'Read the lesson, then take one easy rep.',
          kind: 'learn-cue',
          trainingMode: 'learn-the-cue',
          academyLessonSlug: 'empty-space-cut',
          scenarioIds: ['ESC-01'],
        },
        {
          slug: 'first-reps',
          order: 2,
          title: 'First Reps',
          subtitle: 'Tag and stunt cuts.',
          kind: 'scenario-set',
          trainingMode: 'freeze-frame-read',
          scenarioIds: ['ESC-01', 'ESC-02'],
          prerequisiteNodeSlugs: ['learn-the-cue'],
        },
        {
          slug: 'help-turn-reads',
          order: 3,
          title: 'Help-Turn Reads',
          subtitle: 'Diagonal cuts and corner lifts.',
          kind: 'scenario-set',
          trainingMode: 'freeze-frame-read',
          scenarioIds: ['ESC-03', 'ESC-04'],
          prerequisiteNodeSlugs: ['first-reps'],
        },
        {
          slug: 'replace-the-empty-spot',
          order: 4,
          title: 'Replace the Empty Spot',
          subtitle: 'Slash to the nail-help vacancy.',
          kind: 'scenario-set',
          trainingMode: 'freeze-frame-read',
          scenarioIds: ['ESC-05'],
          prerequisiteNodeSlugs: ['help-turn-reads'],
        },
      ],
      bossChallenge: {
        slug: 'cutter',
        title: 'Boss — Cutter',
        subtitle: '5 reps. No hints. 80% to pass.',
        scenarioIds: [...ESC_IDS],
        passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
        hideDecoderPill: true,
      },
    },
    {
      slug: 'beat-the-closeout',
      order: 3,
      title: 'Beat the Closeout',
      subtitle: 'Read the feet. Then choose: shoot, drive, reset.',
      basketballCue:
        'Closeout defender feet/balance: parallel + forward → drive; squared + balanced → reset; late + short → shoot; high + tilted → pump-and-go; sideways recovery → attack the open hip.',
      decoderTag: 'ADVANTAGE_OR_RESET',
      decoderTags: ['ADVANTAGE_OR_RESET'],
      goal: "Learn when to shoot, drive, or reset based on the defender's feet and momentum.",
      parentSummary:
        "Player distinguishes a closeout that is an advantage from one that isn't, and selects the highest-value response on the catch (catch-and-shoot, rip-and-go, or reset/swing).",
      coachSummary:
        "Player will read the closeout's stance before the catch and choose between shoot, drive, and reset rather than defaulting to a single option.",
      passCriteria: CHAPTER_PASS,
      masteryCriteria: CHAPTER_MASTERY,
      skillNodes: [
        {
          slug: 'learn-the-cue',
          order: 1,
          title: 'Learn the Cue',
          subtitle: 'Read the lesson, then take one easy rep.',
          kind: 'learn-cue',
          trainingMode: 'learn-the-cue',
          academyLessonSlug: 'advantage-or-reset',
          scenarioIds: ['AOR-01'],
        },
        {
          slug: 'go-now',
          order: 2,
          title: 'Go Now',
          subtitle: 'Drive past flat feet.',
          kind: 'scenario-set',
          trainingMode: 'freeze-frame-read',
          scenarioIds: ['AOR-01', 'AOR-02'],
          prerequisiteNodeSlugs: ['learn-the-cue'],
        },
        {
          slug: 'reset-discipline',
          order: 3,
          title: 'Reset Discipline',
          subtitle: 'Swing the ball when the closeout is square.',
          kind: 'scenario-set',
          trainingMode: 'freeze-frame-read',
          scenarioIds: ['AOR-03'],
          prerequisiteNodeSlugs: ['go-now'],
        },
        {
          slug: 'shoot-vs-pump',
          order: 4,
          title: 'Shoot vs Pump',
          subtitle: 'Long closeout, short closeout.',
          kind: 'scenario-set',
          trainingMode: 'freeze-frame-read',
          scenarioIds: ['AOR-04'],
          prerequisiteNodeSlugs: ['reset-discipline'],
        },
        {
          slug: 'open-hip',
          order: 5,
          title: 'Open Hip',
          subtitle: 'Sideways recovery — drive the open hip.',
          kind: 'scenario-set',
          trainingMode: 'freeze-frame-read',
          scenarioIds: ['AOR-05'],
          prerequisiteNodeSlugs: ['shoot-vs-pump'],
        },
      ],
      bossChallenge: {
        slug: 'catch-decider',
        title: 'Boss — Catch Decider',
        subtitle: '5 reps. No hints. 80% to pass.',
        scenarioIds: [...AOR_IDS],
        passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
        hideDecoderPill: true,
      },
    },
    {
      slug: 'punish-the-help',
      order: 4,
      title: 'Punish the Help',
      subtitle: 'When two defenders show up, find the one they left.',
      basketballCue:
        'Two defenders committed to the paint or the ball; a weak-side defender stunting/helping in.',
      decoderTag: 'SKIP_THE_ROTATION',
      decoderTags: ['SKIP_THE_ROTATION'],
      goal: 'Learn to identify help defense and pass behind the rotation.',
      parentSummary:
        'Player recognizes help-side commitments and passes opposite the rotation rather than into traffic. The read that turns drive-and-kick into open threes.',
      coachSummary:
        'Player will identify two-defender commitments and pass *opposite* the rotation, prioritizing the highest-recovery-cost shooter.',
      passCriteria: CHAPTER_PASS,
      masteryCriteria: CHAPTER_MASTERY,
      skillNodes: [
        {
          slug: 'learn-the-cue',
          order: 1,
          title: 'Learn the Cue',
          subtitle: 'Read the lesson, then take one easy rep.',
          kind: 'learn-cue',
          trainingMode: 'learn-the-cue',
          academyLessonSlug: 'skip-the-rotation',
          scenarioIds: ['SKR-01'],
        },
        {
          slug: 'paint-touch',
          order: 2,
          title: 'Paint Touch',
          subtitle: 'Skip cross-court when the help leaves the corner.',
          kind: 'scenario-set',
          trainingMode: 'freeze-frame-read',
          scenarioIds: ['SKR-01'],
          prerequisiteNodeSlugs: ['learn-the-cue'],
        },
        {
          slug: 'pnr-and-post',
          order: 3,
          title: 'PnR & Post Skips',
          subtitle: 'Tagger leaves the corner; double leaves the wing.',
          kind: 'scenario-set',
          trainingMode: 'freeze-frame-read',
          scenarioIds: ['SKR-02', 'SKR-03'],
          prerequisiteNodeSlugs: ['paint-touch'],
        },
        {
          slug: 'second-rotation',
          order: 4,
          title: 'Second Rotation',
          subtitle: 'Drop coverage and X-out skips.',
          kind: 'scenario-set',
          trainingMode: 'freeze-frame-read',
          scenarioIds: ['SKR-04', 'SKR-05'],
          prerequisiteNodeSlugs: ['pnr-and-post'],
        },
      ],
      bossChallenge: {
        slug: 'rotation-reader',
        title: 'Boss — Rotation Reader',
        subtitle: '5 reps. No hints. 80% to pass.',
        scenarioIds: [...SKR_IDS],
        passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
        hideDecoderPill: true,
      },
    },
    {
      slug: 'real-game-mix',
      order: 5,
      title: 'Real Game Mix',
      subtitle: 'Now read the play, not the decoder.',
      basketballCue:
        'All four. The player has to identify the cue before answering — no decoder pill is shown.',
      decoderTag: null,
      decoderTags: [
        'BACKDOOR_WINDOW',
        'EMPTY_SPACE_CUT',
        'ADVANTAGE_OR_RESET',
        'SKIP_THE_ROTATION',
      ],
      goal: 'Make game-like decisions without being told which decoder to use.',
      parentSummary:
        'Player demonstrates cue identification and decision selection across all four foundation reads, mixed and unlabeled. This is the threshold between trainee and decoder.',
      coachSummary:
        'Player will self-identify which read the scenario presents (denial / empty-space / closeout / help rotation) and execute the correct response without a decoder cue.',
      passCriteria: { minBest: 6, minDecoderAccuracy: 0.7 },
      masteryCriteria: { minBest: 8, minDecoderAccuracy: 0.8, minDecoderAttempts: 5 },
      skillNodes: [
        {
          slug: 'mixed-warmup',
          order: 1,
          title: 'Mixed Reads — Warmup',
          subtitle: '5 randomized reps. Decoder pill hidden.',
          kind: 'mixed',
          trainingMode: 'mixed-reads',
          scenarioIds: [...BDW_IDS, ...ESC_IDS, ...AOR_IDS, ...SKR_IDS],
        },
        {
          slug: 'mixed-pressure',
          order: 2,
          title: 'Mixed Reads — Pressure',
          subtitle: '5 reps with a tighter freeze window.',
          kind: 'mixed',
          trainingMode: 'pressure-test',
          scenarioIds: [...BDW_IDS, ...ESC_IDS, ...AOR_IDS, ...SKR_IDS],
          prerequisiteNodeSlugs: ['mixed-warmup'],
        },
      ],
      bossChallenge: {
        slug: 'all-reads',
        title: 'Pathway Boss — All Reads',
        subtitle: '10 mixed reps. 80% to pass.',
        scenarioIds: [...BDW_IDS, ...ESC_IDS, ...AOR_IDS, ...SKR_IDS],
        passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 10 },
        hideDecoderPill: true,
      },
    },
  ],
}

const COMING_SOON: PathwayConfig[] = [
  {
    slug: 'off-ball-weapon',
    title: 'Off-Ball Weapon',
    subtitle: 'Make your defender forget you exist.',
    description:
      'Drift on the stunt. Replace into the vacated wing. Backdoor the ball-watcher. Catch-and-shoot vs. catch-and-attack reads.',
    accentToken: 'info',
    decoderTags: ['EMPTY_SPACE_CUT', 'BACKDOOR_WINDOW', 'ADVANTAGE_OR_RESET'],
    chapters: [
      {
        slug: 'drift-on-the-stunt',
        order: 1,
        title: 'Drift on the Stunt',
        subtitle: 'When his eyes go to the ball, your space opens.',
        basketballCue:
          'Your defender turns his head, hips, or shoulders toward the ball — the floor space behind him is empty.',
        decoderTag: 'EMPTY_SPACE_CUT',
        decoderTags: ['EMPTY_SPACE_CUT'],
        goal: 'Move on the help turn instead of after it; drift into the space your defender just vacated.',
        parentSummary:
          'Player spaces with intent — moves on the defender\'s eyes, not after the rotation completes.',
        coachSummary:
          'Off-ball offense is movement that earns a catch. This chapter trains the drift on the stunt that makes the closeout impossible.',
        passCriteria: CHAPTER_PASS,
        masteryCriteria: CHAPTER_MASTERY,
        skillNodes: [
          {
            slug: 'learn-the-cue',
            order: 1,
            title: 'Learn the Cue',
            subtitle: 'Read the lesson, then take one easy rep.',
            kind: 'learn-cue',
            trainingMode: 'learn-the-cue',
            academyLessonSlug: 'empty-space-cut',
            scenarioIds: ['ESC-01'],
          },
          {
            slug: 'first-drifts',
            order: 2,
            title: 'First Drifts',
            subtitle: 'Two clean help-turn reads.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['ESC-01', 'ESC-02'],
            prerequisiteNodeSlugs: ['learn-the-cue'],
          },
        ],
        bossChallenge: {
          slug: 'drift-boss',
          title: 'Boss — Drifter',
          subtitle: '5 reps. No hints. 80% to pass.',
          scenarioIds: [...ESC_IDS],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
          hideDecoderPill: true,
        },
      },
      {
        slug: 'replace-the-vacated-wing',
        order: 2,
        title: 'Replace the Vacated Wing',
        subtitle: 'Slash into the spot the help just left.',
        basketballCue:
          'A nail-helper or tagger vacates his wing/slot; the open space is the receiving address, not the original spot.',
        decoderTag: 'EMPTY_SPACE_CUT',
        decoderTags: ['EMPTY_SPACE_CUT'],
        goal: 'Read the second-side rotation and replace into the vacated wing instead of holding the original spot.',
        parentSummary:
          'Player makes the second cut — the one that finds the spot the defense just gave up.',
        coachSummary:
          'Spacing is dynamic. This chapter teaches the replace-cut that turns a help rotation into the next clean catch.',
        passCriteria: CHAPTER_PASS,
        masteryCriteria: CHAPTER_MASTERY,
        skillNodes: [
          {
            slug: 'help-turn-reads',
            order: 1,
            title: 'Help-Turn Reads',
            subtitle: 'Diagonal cuts and corner lifts.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['ESC-03', 'ESC-04'],
            prerequisiteNodeSlugs: [],
          },
          {
            slug: 'replace-the-nail',
            order: 2,
            title: 'Replace the Nail',
            subtitle: 'Slash to the nail-help vacancy.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['ESC-05'],
            prerequisiteNodeSlugs: ['help-turn-reads'],
          },
        ],
        bossChallenge: {
          slug: 'replace-boss',
          title: 'Boss — Vacancy Reader',
          subtitle: '5 reps. No hints. 80% to pass.',
          scenarioIds: ['ESC-03', 'ESC-04', 'ESC-05'],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
          hideDecoderPill: true,
        },
      },
      {
        slug: 'backdoor-the-ball-watcher',
        order: 3,
        title: 'Backdoor the Ball-Watcher',
        subtitle: 'He stopped watching you — punish him.',
        basketballCue:
          'Defender\'s hand or foot is in the passing lane; his chest is between the ball and you. The rim window is behind him.',
        decoderTag: 'BACKDOOR_WINDOW',
        decoderTags: ['BACKDOOR_WINDOW'],
        goal: 'Recognize denial as an invitation and back-cut behind the defender before he can recover.',
        parentSummary:
          'Player turns a denied catch into a layup by cutting behind the defender who gave up the rim.',
        coachSummary:
          'Off-ball weapons read the denial as a gift, not a problem. This chapter trains the back-cut that turns the wing into the rim.',
        passCriteria: CHAPTER_PASS,
        masteryCriteria: CHAPTER_MASTERY,
        skillNodes: [
          {
            slug: 'first-back-cuts',
            order: 1,
            title: 'First Back-Cuts',
            subtitle: 'Two clean denials.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['BDW-01', 'BDW-02'],
            prerequisiteNodeSlugs: [],
          },
          {
            slug: 'corner-denials',
            order: 2,
            title: 'Corner Denials',
            subtitle: 'Top-lock from the corner.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['BDW-03'],
            prerequisiteNodeSlugs: ['first-back-cuts'],
          },
        ],
        bossChallenge: {
          slug: 'backdoor-boss',
          title: 'Boss — Backdoor Reader',
          subtitle: '5 reps. No hints. 80% to pass.',
          scenarioIds: [...BDW_IDS],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
          hideDecoderPill: true,
        },
      },
      {
        slug: 'catch-and-shoot-or-attack',
        order: 4,
        title: 'Catch-and-Shoot or Attack',
        subtitle: 'On the catch, the closeout decides.',
        basketballCue:
          'Defender closing out on the catch — read his feet, cushion, and balance to pick shoot vs drive.',
        decoderTag: 'ADVANTAGE_OR_RESET',
        decoderTags: ['ADVANTAGE_OR_RESET'],
        goal: 'Convert the catch the cut earned into the right shot or drive on the closeout.',
        parentSummary:
          'Player finishes the off-ball action with the right catch decision — shoot, drive, or move it.',
        coachSummary:
          'The cut earned the catch; the closeout decides what comes next. This chapter trains the read that completes the off-ball play.',
        passCriteria: CHAPTER_PASS,
        masteryCriteria: CHAPTER_MASTERY,
        skillNodes: [
          {
            slug: 'go-now',
            order: 1,
            title: 'Go Now',
            subtitle: 'Drive past flat feet.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['AOR-01', 'AOR-02'],
            prerequisiteNodeSlugs: [],
          },
          {
            slug: 'shoot-it',
            order: 2,
            title: 'Shoot It',
            subtitle: 'Short or late closeout — release on rhythm.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['AOR-04'],
            prerequisiteNodeSlugs: ['go-now'],
          },
        ],
        bossChallenge: {
          slug: 'weapon-catch-boss',
          title: 'Boss — Catch Decider',
          subtitle: '5 reps. No hints. 80% to pass.',
          scenarioIds: ['AOR-01', 'AOR-02', 'AOR-03', 'AOR-04', 'AOR-05'],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
          hideDecoderPill: true,
        },
      },
      {
        slug: 'off-ball-mix',
        order: 5,
        title: 'Off-Ball Mix',
        subtitle: 'Three reads. No labels. Real game speed.',
        basketballCue:
          'Drift, back-cut, and catch reads, mixed and unlabeled. The player has to name the cue before answering.',
        decoderTag: null,
        decoderTags: ['EMPTY_SPACE_CUT', 'BACKDOOR_WINDOW', 'ADVANTAGE_OR_RESET'],
        goal: 'Identify drift vs back-cut vs catch-read in mixed reps without a decoder pill.',
        parentSummary:
          'Player demonstrates the three off-ball reads in one mixed run — the threshold for "weapon" status.',
        coachSummary:
          'The capstone. Drift, back-cut, or catch decision — every possession asks one of the three.',
        passCriteria: { minBest: 6, minDecoderAccuracy: 0.7 },
        masteryCriteria: { minBest: 8, minDecoderAccuracy: 0.8, minDecoderAttempts: 5 },
        skillNodes: [
          {
            slug: 'mixed-warmup',
            order: 1,
            title: 'Mixed Off-Ball — Warmup',
            subtitle: '5 randomized reps. Decoder pill hidden.',
            kind: 'mixed',
            trainingMode: 'mixed-reads',
            scenarioIds: [...ESC_IDS, ...BDW_IDS, ...AOR_IDS],
          },
          {
            slug: 'mixed-pressure',
            order: 2,
            title: 'Mixed Off-Ball — Pressure',
            subtitle: '5 reps with a tighter freeze window.',
            kind: 'mixed',
            trainingMode: 'pressure-test',
            scenarioIds: [...ESC_IDS, ...BDW_IDS, ...AOR_IDS],
            prerequisiteNodeSlugs: ['mixed-warmup'],
          },
        ],
        bossChallenge: {
          slug: 'off-ball-weapon-boss',
          title: 'Pathway Boss — Off-Ball Weapon',
          subtitle: '10 mixed reps. 80% to pass.',
          scenarioIds: [...ESC_IDS, ...BDW_IDS, ...AOR_IDS],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 10 },
          hideDecoderPill: true,
        },
      },
    ],
    unlockCriteria: { pathwaysMastered: ['complete-iq-foundation'] },
    passCriteria: { minBest: 16, minDecoderAccuracy: 0.7 },
    estimatedMinutes: 60,
    recommendedFor: ['cutter'],
    targetArchetype: 'off-ball-weapon',
    comingSoon: false,
    parentSummary:
      'Player spaces with intent and converts catch opportunities into shots, drives, or extras.',
    coachSummary:
      'Builds the off-ball habit set that earns minutes: drift on the stunt, replace into vacancies, attack the closeout your defender gives you.',
    basketballProblem:
      'Player gets stuck in the corner and gets ignored on defense — same spot, same shot, no advantage.',
    difficultyRange: [2, 4],
  },
  {
    slug: 'closeout-killer',
    title: 'Closeout Killer',
    subtitle: 'Read the feet. Take what they give you.',
    description:
      'Flat feet → drive. Square stance → reset. High close → pump-and-go. Late close → catch-and-shoot. Closeout too hard → backdoor.',
    accentToken: 'xp',
    decoderTags: ['ADVANTAGE_OR_RESET', 'BACKDOOR_WINDOW', 'SKIP_THE_ROTATION'],
    chapters: [
      {
        slug: 'flat-feet-drive',
        order: 1,
        title: 'Flat Feet Means Drive',
        subtitle: 'When his momentum is forward, the lane is yours.',
        basketballCue:
          'Closeout defender with parallel feet and forward weight; lane is open behind him.',
        decoderTag: 'ADVANTAGE_OR_RESET',
        decoderTags: ['ADVANTAGE_OR_RESET'],
        goal: 'Recognize a closeout that committed too far and punish it with a rip-and-drive past the leading foot.',
        parentSummary:
          'Player turns a hard closeout into an attack instead of a hesitation. The first read every shooter needs.',
        coachSummary:
          'Closeouts with momentum forward get blown by. This chapter trains the eye for flat feet and the muscle to attack on the catch.',
        passCriteria: CHAPTER_PASS,
        masteryCriteria: CHAPTER_MASTERY,
        skillNodes: [
          {
            slug: 'learn-the-cue',
            order: 1,
            title: 'Learn the Cue',
            subtitle: 'Read the lesson, then take one easy rep.',
            kind: 'learn-cue',
            trainingMode: 'learn-the-cue',
            academyLessonSlug: 'advantage-or-reset',
            scenarioIds: ['AOR-01'],
          },
          {
            slug: 'first-drives',
            order: 2,
            title: 'First Drives',
            subtitle: 'Two clean flat-feet closeouts.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['AOR-01', 'AOR-02'],
            prerequisiteNodeSlugs: ['learn-the-cue'],
          },
        ],
        bossChallenge: {
          slug: 'flat-feet-boss',
          title: 'Boss — Flat-Feet Reader',
          subtitle: '5 reps. No hints. 80% to pass.',
          scenarioIds: ['AOR-01', 'AOR-02', 'AOR-04', 'AOR-05'],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
          hideDecoderPill: true,
        },
      },
      {
        slug: 'square-stance-reset',
        order: 2,
        title: 'Square Stance, Reset',
        subtitle: 'When the defender is balanced, swing the ball.',
        basketballCue:
          'Closeout defender with feet set under him, chest square, hands up — no advantage to attack.',
        decoderTag: 'ADVANTAGE_OR_RESET',
        decoderTags: ['ADVANTAGE_OR_RESET'],
        goal: 'Tell the difference between a closeout you can attack and one you have to swing past.',
        parentSummary:
          'Player resists the urge to dribble into a balanced defender; reads the stance and moves the ball to keep the advantage alive.',
        coachSummary:
          'Reset discipline is the hardest part of becoming a shooter who plays. This chapter trains the patience to move the ball when the closeout is too good.',
        passCriteria: CHAPTER_PASS,
        masteryCriteria: CHAPTER_MASTERY,
        skillNodes: [
          {
            slug: 'reset-rep',
            order: 1,
            title: 'Reset Rep',
            subtitle: 'Swing it when the defender is square.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['AOR-03'],
            prerequisiteNodeSlugs: [],
          },
        ],
        bossChallenge: {
          slug: 'reset-boss',
          title: 'Boss — Reset Discipline',
          subtitle: '5 reps. No hints. 80% to pass.',
          scenarioIds: ['AOR-02', 'AOR-03', 'AOR-04', 'AOR-05'],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
          hideDecoderPill: true,
        },
      },
      {
        slug: 'catch-and-shoot',
        order: 3,
        title: 'Catch and Shoot',
        subtitle: 'Short closeout, late close — let it fly.',
        basketballCue:
          'Defender still two strides out, hands not yet up, or recovering sideways — the shot is open before the contest arrives.',
        decoderTag: 'ADVANTAGE_OR_RESET',
        decoderTags: ['ADVANTAGE_OR_RESET'],
        goal: 'Read a short or late closeout and release on rhythm instead of putting the ball on the floor.',
        parentSummary:
          'Player takes the catch-and-shoot when the defender gave it up, instead of pump-faking the advantage away.',
        coachSummary:
          'A shooter who shoots in rhythm is a shooter who plays. This chapter trains the eye for a closeout that already lost.',
        passCriteria: CHAPTER_PASS,
        masteryCriteria: CHAPTER_MASTERY,
        skillNodes: [
          {
            slug: 'short-close',
            order: 1,
            title: 'Short Closeout',
            subtitle: 'Defender still has ground to cover; release on the catch.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['AOR-04'],
            prerequisiteNodeSlugs: [],
          },
          {
            slug: 'open-hip',
            order: 2,
            title: 'Open Hip',
            subtitle: 'Sideways recovery — drive his open hip OR shoot it.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['AOR-05'],
            prerequisiteNodeSlugs: ['short-close'],
          },
        ],
        bossChallenge: {
          slug: 'catch-shoot-boss',
          title: 'Boss — Catch & Shoot',
          subtitle: '5 reps. No hints. 80% to pass.',
          scenarioIds: ['AOR-03', 'AOR-04', 'AOR-05'],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
          hideDecoderPill: true,
        },
      },
      {
        slug: 'closeout-into-help',
        order: 4,
        title: 'Closeout Into Help',
        subtitle: 'They closed out hard and brought help. Find the shooter they left.',
        basketballCue:
          'Long closeout PLUS a help-side stunt — the abandoned shooter is the highest-value pass, not the drive.',
        decoderTag: 'SKIP_THE_ROTATION',
        decoderTags: ['SKIP_THE_ROTATION', 'ADVANTAGE_OR_RESET'],
        goal: 'When the closeout brings help, kick to the abandoned shooter instead of driving into traffic.',
        parentSummary:
          'Player recognizes when a closeout was an advantage AND a trap, and chooses the kick-out over the contested drive.',
        coachSummary:
          'The best shooters punish the cleanup help. This chapter pairs the closeout read with the rotation read so the next pass is automatic.',
        passCriteria: CHAPTER_PASS,
        masteryCriteria: CHAPTER_MASTERY,
        skillNodes: [
          {
            slug: 'kick-the-stunt',
            order: 1,
            title: 'Kick the Stunt',
            subtitle: 'Tagger stepped up — the corner is yours.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['SKR-01', 'SKR-02'],
            prerequisiteNodeSlugs: [],
          },
        ],
        bossChallenge: {
          slug: 'closeout-help-boss',
          title: 'Boss — Closeout + Help',
          subtitle: '5 reps. No hints. 80% to pass.',
          scenarioIds: ['AOR-01', 'AOR-04', 'AOR-05', 'SKR-01', 'SKR-02'],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
          hideDecoderPill: true,
        },
      },
      {
        slug: 'closeout-mix',
        order: 5,
        title: 'Closeout Mix',
        subtitle: 'Five closeouts. Five reads. No labels.',
        basketballCue:
          'Every kind of closeout, unlabeled. The player has to name the read before answering.',
        decoderTag: null,
        decoderTags: ['ADVANTAGE_OR_RESET', 'SKIP_THE_ROTATION'],
        goal: 'Pick the right read on every closeout — drive, reset, shoot, or kick — without a decoder pill to help.',
        parentSummary:
          'Player demonstrates closeout cue identification across all four sub-reads, mixed and unlabeled.',
        coachSummary:
          'The boss chapter. Drive, reset, shoot, or kick — every catch becomes a real decision.',
        passCriteria: { minBest: 6, minDecoderAccuracy: 0.7 },
        masteryCriteria: { minBest: 8, minDecoderAccuracy: 0.8, minDecoderAttempts: 5 },
        skillNodes: [
          {
            slug: 'mixed-warmup',
            order: 1,
            title: 'Mixed Closeouts — Warmup',
            subtitle: '5 randomized reps. Decoder pill hidden.',
            kind: 'mixed',
            trainingMode: 'mixed-reads',
            scenarioIds: [...AOR_IDS, 'SKR-01', 'SKR-02'],
          },
          {
            slug: 'mixed-pressure',
            order: 2,
            title: 'Mixed Closeouts — Pressure',
            subtitle: '5 reps with a tighter freeze window.',
            kind: 'mixed',
            trainingMode: 'pressure-test',
            scenarioIds: [...AOR_IDS, 'SKR-01', 'SKR-02'],
            prerequisiteNodeSlugs: ['mixed-warmup'],
          },
        ],
        bossChallenge: {
          slug: 'closeout-killer-boss',
          title: 'Pathway Boss — Closeout Killer',
          subtitle: '10 mixed reps. 80% to pass.',
          scenarioIds: [...AOR_IDS, 'SKR-01', 'SKR-02'],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 10 },
          hideDecoderPill: true,
        },
      },
    ],
    unlockCriteria: { pathwaysMastered: ['complete-iq-foundation'] },
    passCriteria: { minBest: 16, minDecoderAccuracy: 0.7 },
    estimatedMinutes: 60,
    recommendedFor: ['attacker'],
    targetArchetype: 'attacker',
    comingSoon: false,
    parentSummary:
      'Player distinguishes a closeout that is an advantage from one that isn’t, and selects between shoot, drive, and reset.',
    coachSummary:
      'Closeout decisions decide most half-court possessions. This Pathway turns the catch into an instant read instead of a panic.',
    basketballProblem:
      'Player either rushes a contested three or holds too long and gives the advantage back.',
    difficultyRange: [2, 4],
  },
  {
    slug: 'help-defense-punisher',
    title: 'Help Defense Punisher',
    subtitle: 'When two defenders show up, find the one they left.',
    description:
      'Read low-man tag. Skip behind the rotation. Punish the X-out. Read who came to bracket.',
    accentToken: 'iq',
    decoderTags: ['SKIP_THE_ROTATION', 'EMPTY_SPACE_CUT', 'ADVANTAGE_OR_RESET'],
    chapters: [
      {
        slug: 'read-the-low-man-tag',
        order: 1,
        title: 'Read the Low-Man Tag',
        subtitle: "The tagger left his man. You don't have to.",
        basketballCue:
          'Weak-side low-man stunts up or fully steps into the lane — the corner shooter he was guarding is alone.',
        decoderTag: 'SKIP_THE_ROTATION',
        decoderTags: ['SKIP_THE_ROTATION'],
        goal: 'Recognize a low-man tag and deliver the skip to the abandoned shooter instead of forcing into the lane.',
        parentSummary:
          'Player learns the most common help rotation in basketball — the low-man tag — and the punishment that turns it into a corner three.',
        coachSummary:
          'The low-man tag is the staple help rotation. This chapter trains the read that turns a paint touch into a clean kick-out.',
        passCriteria: CHAPTER_PASS,
        masteryCriteria: CHAPTER_MASTERY,
        skillNodes: [
          {
            slug: 'learn-the-cue',
            order: 1,
            title: 'Learn the Cue',
            subtitle: 'Read the lesson, then take one easy rep.',
            kind: 'learn-cue',
            trainingMode: 'learn-the-cue',
            academyLessonSlug: 'skip-the-rotation',
            scenarioIds: ['SKR-01'],
          },
          {
            slug: 'first-tags',
            order: 2,
            title: 'First Tags',
            subtitle: 'Two clean tagger reads.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['SKR-01', 'SKR-02'],
            prerequisiteNodeSlugs: ['learn-the-cue'],
          },
          {
            slug: 'stunt-vs-commit',
            order: 3,
            title: 'Stunt vs Commit',
            subtitle: 'Foot in the lane vs both feet — different reads.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['ESC-04'],
            prerequisiteNodeSlugs: ['first-tags'],
          },
        ],
        bossChallenge: {
          slug: 'tag-reader',
          title: 'Boss — Tag Reader',
          subtitle: '5 reps. No hints. 80% to pass.',
          scenarioIds: ['SKR-01', 'SKR-02', 'ESC-04'],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
          hideDecoderPill: true,
        },
      },
      {
        slug: 'skip-behind-the-rotation',
        order: 2,
        title: 'Skip Behind the Rotation',
        subtitle: 'Pass to the spot the rotation just left.',
        basketballCue:
          'Two defenders moving into the same address — the open address is always the one BEHIND the rotation, not into it.',
        decoderTag: 'SKIP_THE_ROTATION',
        decoderTags: ['SKIP_THE_ROTATION'],
        goal: 'Read the second defender on the move and skip to the man he left, not the one he\'s covering.',
        parentSummary:
          'Player resists driving into the help and learns to read who the help came from, then pass to that man.',
        coachSummary:
          'Most help-rotation turnovers come from passing INTO traffic instead of BEHIND it. This chapter trains the spatial read that prevents them.',
        passCriteria: CHAPTER_PASS,
        masteryCriteria: CHAPTER_MASTERY,
        skillNodes: [
          {
            slug: 'pnr-and-post',
            order: 1,
            title: 'PnR & Post Skips',
            subtitle: 'Tagger leaves the corner; double leaves the wing.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['SKR-02', 'SKR-03'],
            prerequisiteNodeSlugs: [],
          },
          {
            slug: 'second-rotation',
            order: 2,
            title: 'Second Rotation',
            subtitle: 'Drop coverage and second-side skips.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['SKR-04'],
            prerequisiteNodeSlugs: ['pnr-and-post'],
          },
        ],
        bossChallenge: {
          slug: 'rotation-skipper',
          title: 'Boss — Rotation Skipper',
          subtitle: '5 reps. No hints. 80% to pass.',
          scenarioIds: ['SKR-02', 'SKR-03', 'SKR-04'],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
          hideDecoderPill: true,
        },
      },
      {
        slug: 'punish-the-x-out',
        order: 3,
        title: 'Punish the X-Out',
        subtitle: 'The second rotation is the slowest. Hit it.',
        basketballCue:
          'The first help recovers; a second defender X-outs to cover the kick. The slot he just left is the open one.',
        decoderTag: 'SKIP_THE_ROTATION',
        decoderTags: ['SKIP_THE_ROTATION'],
        goal: 'Read the X-out rotation and skip to the weak slot the second helper vacated.',
        parentSummary:
          'Player learns the harder, two-step rotation read — the X-out — and the pass that beats it.',
        coachSummary:
          'X-outs cover one shooter and uncover another. This chapter trains the read that finds the second uncovered shooter, not the first.',
        passCriteria: CHAPTER_PASS,
        masteryCriteria: CHAPTER_MASTERY,
        skillNodes: [
          {
            slug: 'x-out-reads',
            order: 1,
            title: 'X-Out Reads',
            subtitle: 'Read the second rotation, find the open slot.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['SKR-05'],
            prerequisiteNodeSlugs: [],
          },
        ],
        bossChallenge: {
          slug: 'x-out-boss',
          title: 'Boss — X-Out Punisher',
          subtitle: '5 reps. No hints. 80% to pass.',
          scenarioIds: ['SKR-04', 'SKR-05'],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
          hideDecoderPill: true,
        },
      },
      {
        slug: 'read-who-came',
        order: 4,
        title: 'Read Who Came',
        subtitle: 'When the help arrives, the catch decides what comes next.',
        basketballCue:
          'A help defender flies at you on the catch — read his stance to choose between attack, reset, and shoot.',
        decoderTag: 'ADVANTAGE_OR_RESET',
        decoderTags: ['ADVANTAGE_OR_RESET'],
        goal: 'After a help rotation arrives at YOUR catch, pick attack, reset, or shoot based on his feet and cushion.',
        parentSummary:
          'Player finishes the help-rotation read with the right catch decision — the closeout that the rotation became.',
        coachSummary:
          'Punishing help is two reads: the skip AND the next catch. This chapter trains the second read so the punishment doesn\'t stop at one pass.',
        passCriteria: CHAPTER_PASS,
        masteryCriteria: CHAPTER_MASTERY,
        skillNodes: [
          {
            slug: 'attack-the-helper',
            order: 1,
            title: 'Attack the Helper',
            subtitle: 'Flat-feet recovery — drive past it.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['AOR-01', 'AOR-02'],
            prerequisiteNodeSlugs: [],
          },
          {
            slug: 'reset-the-helper',
            order: 2,
            title: 'Reset the Helper',
            subtitle: 'Square stance — swing it.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['AOR-03'],
            prerequisiteNodeSlugs: ['attack-the-helper'],
          },
          {
            slug: 'shoot-over-the-helper',
            order: 3,
            title: 'Shoot Over the Helper',
            subtitle: 'Short or late close — release on rhythm.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['AOR-04', 'AOR-05'],
            prerequisiteNodeSlugs: ['reset-the-helper'],
          },
        ],
        bossChallenge: {
          slug: 'helper-catch-boss',
          title: 'Boss — Helper Catch Reader',
          subtitle: '5 reps. No hints. 80% to pass.',
          scenarioIds: [...AOR_IDS],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
          hideDecoderPill: true,
        },
      },
      {
        slug: 'help-punisher-mix',
        order: 5,
        title: 'Help-Punisher Mix',
        subtitle: 'Skip, X-out, or catch read — name the cue before you answer.',
        basketballCue:
          'Tags, X-outs, and closeouts mixed and unlabeled. The player has to name the rotation type before picking the pass.',
        decoderTag: null,
        decoderTags: ['SKIP_THE_ROTATION', 'EMPTY_SPACE_CUT', 'ADVANTAGE_OR_RESET'],
        goal: 'Identify the rotation type (low-man tag, X-out, or arriving closeout) and pick the punishing read without a decoder pill.',
        parentSummary:
          'Player demonstrates the full help-punisher tree — read the rotation, identify the abandoned man, deliver the right pass — in mixed reps.',
        coachSummary:
          'The capstone. Real possessions don\'t announce which rotation they are; this run forces the player to read it cold.',
        passCriteria: { minBest: 6, minDecoderAccuracy: 0.7 },
        masteryCriteria: { minBest: 8, minDecoderAccuracy: 0.8, minDecoderAttempts: 5 },
        skillNodes: [
          {
            slug: 'mixed-warmup',
            order: 1,
            title: 'Mixed Help — Warmup',
            subtitle: '5 randomized reps. Decoder pill hidden.',
            kind: 'mixed',
            trainingMode: 'mixed-reads',
            scenarioIds: [...SKR_IDS, ...AOR_IDS, 'ESC-04'],
          },
          {
            slug: 'mixed-pressure',
            order: 2,
            title: 'Mixed Help — Pressure',
            subtitle: '5 reps with a tighter freeze window.',
            kind: 'mixed',
            trainingMode: 'pressure-test',
            scenarioIds: [...SKR_IDS, ...AOR_IDS, 'ESC-04'],
            prerequisiteNodeSlugs: ['mixed-warmup'],
          },
        ],
        bossChallenge: {
          slug: 'help-punisher-boss',
          title: 'Pathway Boss — Help Defense Punisher',
          subtitle: '10 mixed reps. 80% to pass.',
          scenarioIds: [...SKR_IDS, ...AOR_IDS, 'ESC-04'],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 10 },
          hideDecoderPill: true,
        },
      },
    ],
    unlockCriteria: { pathwaysMastered: ['complete-iq-foundation'] },
    passCriteria: { minBest: 16, minDecoderAccuracy: 0.7 },
    estimatedMinutes: 75,
    recommendedFor: ['connector'],
    targetArchetype: 'help-defender-punisher',
    comingSoon: false,
    parentSummary:
      'Player identifies help-defense commitments and passes opposite the rotation rather than into traffic.',
    coachSummary:
      'The fastest way to make your team better is to find the shooter the help left. This Pathway trains that read until it is automatic.',
    basketballProblem: 'Player forces the layup into help instead of finding the abandoned shooter.',
    difficultyRange: [3, 5],
  },
  {
    slug: 'point-guard-brain',
    title: 'Point Guard Brain',
    subtitle: 'Read the coverage before you read the help.',
    description:
      'Read drop coverage. Skip past the first helper. Beat the X-out. Reset when the catch is not an advantage.',
    accentToken: 'iq',
    decoderTags: ['READ_THE_COVERAGE', 'SKIP_THE_ROTATION', 'ADVANTAGE_OR_RESET'],
    chapters: [
      {
        slug: 'read-the-drop',
        order: 1,
        title: 'Read the Drop',
        subtitle: 'When the big stays back, the pocket is yours.',
        basketballCue:
          'On the high ball-screen, the screen defender sits below the level of the screen — his chest is back, feet pointing toward his own rim.',
        decoderTag: 'READ_THE_COVERAGE',
        decoderTags: ['READ_THE_COVERAGE'],
        goal: 'Read the screen defender on a high ball-screen and pick pull-up, snake, or kick based on his posture and the help.',
        parentSummary:
          'Player recognizes drop coverage on the high pick-and-roll and chooses between the pocket pull-up, the deep-drop snake, and the kick-out when a help defender tags.',
        coachSummary:
          'PnR ball-handlers who can read the screen defender from the first dribble unlock the offense. This chapter trains the three drop reads in order: pocket, snake, and kick-the-tag.',
        passCriteria: CHAPTER_PASS,
        masteryCriteria: CHAPTER_MASTERY,
        skillNodes: [
          {
            slug: 'learn-the-cue',
            order: 1,
            title: 'Learn the Cue',
            subtitle: 'Read the lesson, then take one easy rep.',
            kind: 'learn-cue',
            trainingMode: 'learn-the-cue',
            academyLessonSlug: 'advantage-or-reset',
            scenarioIds: ['DROP-01'],
          },
          {
            slug: 'pocket-pull-up',
            order: 2,
            title: 'Pocket Pull-Up',
            subtitle: 'Drop chest below the screen — take the pocket two.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['DROP-01', 'DROP-01-MIRROR'],
            prerequisiteNodeSlugs: ['learn-the-cue'],
          },
          {
            slug: 'deep-drop-snake',
            order: 3,
            title: 'Deep Drop, Snake It',
            subtitle: 'When the drop is deeper, snake the dribble downhill.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['DROP-02', 'DROP-02-MIRROR'],
            prerequisiteNodeSlugs: ['pocket-pull-up'],
          },
          {
            slug: 'kick-the-tag',
            order: 4,
            title: 'Kick the Tag',
            subtitle: 'Low-man steps up — drop dies, corner opens.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['DROP-03', 'DROP-03-MIRROR'],
            prerequisiteNodeSlugs: ['deep-drop-snake'],
          },
        ],
        bossChallenge: {
          slug: 'drop-reader',
          title: 'Boss — Drop Reader',
          subtitle: '6 reps. No hints. 80% to pass.',
          scenarioIds: [...DROP_IDS],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 6 },
          hideDecoderPill: true,
        },
      },
      {
        slug: 'skip-past-the-first-helper',
        order: 2,
        title: 'Skip Past the First Helper',
        subtitle: 'You drew the help. The shooter he left is open.',
        basketballCue:
          'A weak-side helper steps up to wall off your drive — the man he was guarding is alone in the corner or on the wing.',
        decoderTag: 'SKIP_THE_ROTATION',
        decoderTags: ['SKIP_THE_ROTATION'],
        goal: 'On the live dribble, read the first helper who committed and skip to the shooter he abandoned instead of forcing a finish.',
        parentSummary:
          'Player learns the PG version of the skip-the-rotation read — on the drive, find the shooter the help left and deliver the pass before the recovery.',
        coachSummary:
          'A driving PG who can\'t read help becomes a turnover machine. This chapter trains the look-opposite-the-help skip that turns paint pressure into a clean kick-out.',
        passCriteria: CHAPTER_PASS,
        masteryCriteria: CHAPTER_MASTERY,
        skillNodes: [
          {
            slug: 'learn-the-cue',
            order: 1,
            title: 'Learn the Cue',
            subtitle: 'Read the lesson, then take one easy rep.',
            kind: 'learn-cue',
            trainingMode: 'learn-the-cue',
            academyLessonSlug: 'skip-the-rotation',
            scenarioIds: ['SKR-01'],
          },
          {
            slug: 'corner-tag-skips',
            order: 2,
            title: 'Corner Tag Skips',
            subtitle: 'Tagger leaves the corner — hit the shooter.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['SKR-01', 'SKR-02'],
            prerequisiteNodeSlugs: ['learn-the-cue'],
          },
          {
            slug: 'pnr-and-post-skips',
            order: 3,
            title: 'PnR & Post Skips',
            subtitle: 'Read the doubler off the screen — skip the man he left.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['SKR-03'],
            prerequisiteNodeSlugs: ['corner-tag-skips'],
          },
        ],
        bossChallenge: {
          slug: 'first-helper-skipper',
          title: 'Boss — First-Helper Skipper',
          subtitle: '5 reps. No hints. 80% to pass.',
          scenarioIds: ['SKR-01', 'SKR-02', 'SKR-03'],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
          hideDecoderPill: true,
        },
      },
      {
        slug: 'beat-the-x-out',
        order: 3,
        title: 'Beat the X-Out',
        subtitle: 'The slow rotation is the open one.',
        basketballCue:
          'First help recovers; a second defender X-outs to cover the kick. The slot he just vacated is open by a step.',
        decoderTag: 'SKIP_THE_ROTATION',
        decoderTags: ['SKIP_THE_ROTATION'],
        goal: 'Read the X-out rotation off your drive and skip the ball to the slot the second helper had to leave.',
        parentSummary:
          'Player handles the harder two-step rotation read — the X-out — and finds the second open shooter instead of forcing into the first recovery.',
        coachSummary:
          'X-outs are how teams survive the first kick. The PG who beats them with one more pass is the one who breaks defenses.',
        passCriteria: CHAPTER_PASS,
        masteryCriteria: CHAPTER_MASTERY,
        skillNodes: [
          {
            slug: 'second-rotation-reads',
            order: 1,
            title: 'Second-Rotation Reads',
            subtitle: 'Read the X-out, hit the abandoned slot.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['SKR-04', 'SKR-05'],
            prerequisiteNodeSlugs: [],
          },
        ],
        bossChallenge: {
          slug: 'x-out-beater',
          title: 'Boss — X-Out Beater',
          subtitle: '5 reps. No hints. 80% to pass.',
          scenarioIds: ['SKR-04', 'SKR-05'],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
          hideDecoderPill: true,
        },
      },
      {
        slug: 'reset-discipline',
        order: 4,
        title: 'Reset Discipline',
        subtitle: 'Not every catch is an advantage. Swing it.',
        basketballCue:
          'Closing defender arrives balanced, square, with cushion — no opening to shoot or drive. The right answer is the next pass, not your own.',
        decoderTag: 'ADVANTAGE_OR_RESET',
        decoderTags: ['ADVANTAGE_OR_RESET'],
        goal: 'Read the closeout on the catch and choose reset over force — only attack when the defender\'s stance gives you the advantage.',
        parentSummary:
          'Player learns when to keep the ball moving instead of dribbling into a wall. The reset is what gets the offense to the second side.',
        coachSummary:
          'PG turnovers compound when the first read is "I have to score." This chapter trains the reset read — the discipline to swing the ball when the closeout doesn\'t offer an advantage.',
        passCriteria: CHAPTER_PASS,
        masteryCriteria: CHAPTER_MASTERY,
        skillNodes: [
          {
            slug: 'learn-the-cue',
            order: 1,
            title: 'Learn the Cue',
            subtitle: 'Read the lesson, then take one easy rep.',
            kind: 'learn-cue',
            trainingMode: 'learn-the-cue',
            academyLessonSlug: 'advantage-or-reset',
            scenarioIds: ['AOR-01'],
          },
          {
            slug: 'flat-feet-go',
            order: 2,
            title: 'Flat Feet Means Go',
            subtitle: 'Recovery stopped — attack the closeout.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['AOR-01', 'AOR-02'],
            prerequisiteNodeSlugs: ['learn-the-cue'],
          },
          {
            slug: 'square-stance-swing',
            order: 3,
            title: 'Square Stance, Swing It',
            subtitle: 'Balanced defender — reset to the next side.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['AOR-03'],
            prerequisiteNodeSlugs: ['flat-feet-go'],
          },
          {
            slug: 'long-vs-short-close',
            order: 4,
            title: 'Long vs Short Close',
            subtitle: 'Long close — shoot. Short close — attack.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['AOR-04', 'AOR-05'],
            prerequisiteNodeSlugs: ['square-stance-swing'],
          },
        ],
        bossChallenge: {
          slug: 'reset-boss',
          title: 'Boss — Reset Decider',
          subtitle: '5 reps. No hints. 80% to pass.',
          scenarioIds: [...AOR_IDS],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
          hideDecoderPill: true,
        },
      },
      {
        slug: 'point-guard-mix',
        order: 5,
        title: 'Point Guard Mix',
        subtitle: 'Coverage, rotation, or catch — name it before you answer.',
        basketballCue:
          'PnR coverages, help rotations, and closeouts mixed and unlabeled. The PG has to identify the read before picking the pass.',
        decoderTag: null,
        decoderTags: ['READ_THE_COVERAGE', 'SKIP_THE_ROTATION', 'ADVANTAGE_OR_RESET'],
        goal: 'Identify the read type (coverage, rotation, catch) and execute the right answer without a decoder pill.',
        parentSummary:
          'Player demonstrates the full point-guard read tree — coverage on the screen, rotation on the drive, decision on the catch — across mixed reps.',
        coachSummary:
          'The capstone. Real possessions don\'t announce which read they are; this run forces the PG to read it cold across the three jobs he holds every trip down.',
        passCriteria: { minBest: 7, minDecoderAccuracy: 0.7 },
        masteryCriteria: { minBest: 9, minDecoderAccuracy: 0.8, minDecoderAttempts: 6 },
        skillNodes: [
          {
            slug: 'mixed-warmup',
            order: 1,
            title: 'Mixed PG — Warmup',
            subtitle: '6 randomized reps. Decoder pill hidden.',
            kind: 'mixed',
            trainingMode: 'mixed-reads',
            scenarioIds: [...DROP_IDS, ...SKR_IDS, ...AOR_IDS],
          },
          {
            slug: 'mixed-pressure',
            order: 2,
            title: 'Mixed PG — Pressure',
            subtitle: '6 reps with a tighter freeze window.',
            kind: 'mixed',
            trainingMode: 'pressure-test',
            scenarioIds: [...DROP_IDS, ...SKR_IDS, ...AOR_IDS],
            prerequisiteNodeSlugs: ['mixed-warmup'],
          },
        ],
        bossChallenge: {
          slug: 'point-guard-boss',
          title: 'Pathway Boss — Point Guard Brain',
          subtitle: '12 mixed reps. 80% to pass.',
          scenarioIds: [...DROP_IDS, ...SKR_IDS, ...AOR_IDS],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 12 },
          hideDecoderPill: true,
        },
      },
    ],
    unlockCriteria: { pathwaysMastered: ['complete-iq-foundation'] },
    passCriteria: { minBest: 16, minDecoderAccuracy: 0.7 },
    estimatedMinutes: 75,
    recommendedFor: ['floor-general'],
    targetArchetype: 'floor-general',
    comingSoon: false,
    parentSummary:
      'Player reads pick-and-roll coverage on the screen, finds the helper the drive draws, and disciplines the catch — the three jobs every point guard holds every trip down.',
    coachSummary:
      'PGs run the offense by reading three things in order: the coverage on the screen, the rotation on the drive, and the closeout on the catch. This Pathway trains all three until the read order is automatic.',
    basketballProblem:
      'Player isn’t seeing the second-side action; runs the same play into a wall.',
    difficultyRange: [3, 5],
  },
  {
    slug: 'wing-decision-maker',
    title: 'Wing Decision-Maker',
    subtitle: 'Catch. Read. Shoot, drive, or move it.',
    description: 'Catch decisions. Live-dribble reads. Shoot/drive/skip triples.',
    accentToken: 'brand',
    decoderTags: [
      'ADVANTAGE_OR_RESET',
      'BACKDOOR_WINDOW',
      'EMPTY_SPACE_CUT',
      'SKIP_THE_ROTATION',
    ],
    chapters: [
      {
        slug: 'catch-and-decide',
        order: 1,
        title: 'Catch and Decide',
        subtitle: 'Three answers live on every catch.',
        basketballCue:
          'Defender closes out on your catch. His stance — feet, balance, cushion, length of the close — decides which of shoot / drive / reset is the right answer.',
        decoderTag: 'ADVANTAGE_OR_RESET',
        decoderTags: ['ADVANTAGE_OR_RESET'],
        goal: 'Read the closeout on every catch and instantly pick shoot, drive, or reset — no freeze, no default.',
        parentSummary:
          'Player learns the wing\'s primary job: every catch is a three-way decision, and the closing defender tells you which one to pick.',
        coachSummary:
          'Catch-and-freeze is the #1 wing failure. This chapter trains the three-way read until shoot/drive/reset is the first thought, not the third.',
        passCriteria: CHAPTER_PASS,
        masteryCriteria: CHAPTER_MASTERY,
        skillNodes: [
          {
            slug: 'learn-the-cue',
            order: 1,
            title: 'Learn the Cue',
            subtitle: 'Read the lesson, then take one easy rep.',
            kind: 'learn-cue',
            trainingMode: 'learn-the-cue',
            academyLessonSlug: 'advantage-or-reset',
            scenarioIds: ['AOR-01'],
          },
          {
            slug: 'flat-feet-attack',
            order: 2,
            title: 'Flat Feet — Attack',
            subtitle: 'Closeout stopped — go past it on the catch.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['AOR-01', 'AOR-02'],
            prerequisiteNodeSlugs: ['learn-the-cue'],
          },
          {
            slug: 'long-close-shoot',
            order: 3,
            title: 'Long Close — Shoot',
            subtitle: 'Late, low-hand close — release on rhythm.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['AOR-04', 'AOR-05'],
            prerequisiteNodeSlugs: ['flat-feet-attack'],
          },
          {
            slug: 'square-stance-swing',
            order: 4,
            title: 'Square Stance — Swing It',
            subtitle: 'Balanced defender — reset to the next side.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['AOR-03'],
            prerequisiteNodeSlugs: ['long-close-shoot'],
          },
        ],
        bossChallenge: {
          slug: 'wing-catch-boss',
          title: 'Boss — Catch Decider',
          subtitle: '5 reps. No hints. 80% to pass.',
          scenarioIds: [...AOR_IDS],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
          hideDecoderPill: true,
        },
      },
      {
        slug: 'backdoor-when-denied',
        order: 2,
        title: 'Backdoor When Denied',
        subtitle: 'Hand in the lane means the rim is open.',
        basketballCue:
          'Defender extends a hand or foot into the passing lane — chest between ball and receiver. The lane closed means the rim opened.',
        decoderTag: 'BACKDOOR_WINDOW',
        decoderTags: ['BACKDOOR_WINDOW'],
        goal: 'Read denial pressure and counter with a back-cut instead of fighting the spot.',
        parentSummary:
          'Player recognizes a denied passing lane on the wing and counters with the back-cut — the read every wing needs against face-guarding.',
        coachSummary:
          'Wings who hold the spot against denial give up the possession. This chapter trains the back-cut counter — the first answer to ball-side denial.',
        passCriteria: CHAPTER_PASS,
        masteryCriteria: CHAPTER_MASTERY,
        skillNodes: [
          {
            slug: 'learn-the-cue',
            order: 1,
            title: 'Learn the Cue',
            subtitle: 'Read the lesson, then take one easy rep.',
            kind: 'learn-cue',
            trainingMode: 'learn-the-cue',
            academyLessonSlug: 'backdoor-window',
            scenarioIds: ['BDW-01'],
          },
          {
            slug: 'wing-back-cuts',
            order: 2,
            title: 'Wing Back-Cuts',
            subtitle: 'Hand in the lane on the wing — cut behind.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['BDW-01', 'BDW-02'],
            prerequisiteNodeSlugs: ['learn-the-cue'],
          },
          {
            slug: 'disguised-denial',
            order: 3,
            title: 'Disguised Denial',
            subtitle: 'Foot creeping into the lane counts too.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['BDW-03', 'BDW-04'],
            prerequisiteNodeSlugs: ['wing-back-cuts'],
          },
          {
            slug: 'late-clock-corner',
            order: 4,
            title: 'Late-Clock Corner',
            subtitle: 'Same denial read, shot-clock pressure.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['BDW-05'],
            prerequisiteNodeSlugs: ['disguised-denial'],
          },
        ],
        bossChallenge: {
          slug: 'wing-backdoor-boss',
          title: 'Boss — Backdoor Reader',
          subtitle: '5 reps. No hints. 80% to pass.',
          scenarioIds: [...BDW_IDS],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
          hideDecoderPill: true,
        },
      },
      {
        slug: 'move-when-eyes-leave',
        order: 3,
        title: 'Move When Eyes Leave',
        subtitle: 'Defender turns to help — your spot just got smaller.',
        basketballCue:
          'Your defender turns his head to help on the ball — eyes off you. The cut or the relocation becomes free.',
        decoderTag: 'EMPTY_SPACE_CUT',
        decoderTags: ['EMPTY_SPACE_CUT'],
        goal: 'Read your defender\'s eyes/turn off-ball and move to the empty space — cut, drift, or replace.',
        parentSummary:
          'Player recognizes when his defender has turned attention away and uses the moment to drift, cut, or replace into open space.',
        coachSummary:
          'Wings who stand watch the ball get scored on; wings who move when their defender turns get layups. This chapter trains the off-ball read.',
        passCriteria: CHAPTER_PASS,
        masteryCriteria: CHAPTER_MASTERY,
        skillNodes: [
          {
            slug: 'learn-the-cue',
            order: 1,
            title: 'Learn the Cue',
            subtitle: 'Read the lesson, then take one easy rep.',
            kind: 'learn-cue',
            trainingMode: 'learn-the-cue',
            academyLessonSlug: 'empty-space-cut',
            scenarioIds: ['ESC-01'],
          },
          {
            slug: 'help-turn-reads',
            order: 2,
            title: 'Help-Turn Reads',
            subtitle: 'Eyes turn — the spot opens.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['ESC-01', 'ESC-02'],
            prerequisiteNodeSlugs: ['learn-the-cue'],
          },
          {
            slug: 'drift-and-replace',
            order: 3,
            title: 'Drift and Replace',
            subtitle: 'Tagger stunts — drift opposite; nail vacates — replace it.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['ESC-03', 'ESC-04'],
            prerequisiteNodeSlugs: ['help-turn-reads'],
          },
          {
            slug: 'cut-the-nail',
            order: 4,
            title: 'Cut the Nail',
            subtitle: 'When the wing defender helps low, the nail is yours.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['ESC-05'],
            prerequisiteNodeSlugs: ['drift-and-replace'],
          },
        ],
        bossChallenge: {
          slug: 'wing-cutter-boss',
          title: 'Boss — Cutter',
          subtitle: '5 reps. No hints. 80% to pass.',
          scenarioIds: [...ESC_IDS],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
          hideDecoderPill: true,
        },
      },
      {
        slug: 'drive-and-skip',
        order: 4,
        title: 'Drive and Skip',
        subtitle: 'Once you go, find the shooter the help left.',
        basketballCue:
          'You attacked the closeout; a helper stunted or rotated. The man he left is open by the time you reach the second dribble.',
        decoderTag: 'SKIP_THE_ROTATION',
        decoderTags: ['SKIP_THE_ROTATION'],
        goal: 'On the live dribble after the drive, read the first helper who came and skip to the abandoned shooter rather than forcing the finish.',
        parentSummary:
          'Player handles the wing\'s second decision — after the drive, deliver the skip pass to the shooter the help abandoned.',
        coachSummary:
          'Wings who can drive but can\'t pass off the drive are easy to guard. This chapter trains the live-dribble skip — the pass that turns a stop into a clean three.',
        passCriteria: CHAPTER_PASS,
        masteryCriteria: CHAPTER_MASTERY,
        skillNodes: [
          {
            slug: 'learn-the-cue',
            order: 1,
            title: 'Learn the Cue',
            subtitle: 'Read the lesson, then take one easy rep.',
            kind: 'learn-cue',
            trainingMode: 'learn-the-cue',
            academyLessonSlug: 'skip-the-rotation',
            scenarioIds: ['SKR-01'],
          },
          {
            slug: 'corner-tag-skips',
            order: 2,
            title: 'Corner Tag Skips',
            subtitle: 'Low-man tagged — skip the corner.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['SKR-01', 'SKR-02'],
            prerequisiteNodeSlugs: ['learn-the-cue'],
          },
          {
            slug: 'pnr-post-skips',
            order: 3,
            title: 'PnR & Post Skips',
            subtitle: 'Doubler left the wing — hit him.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['SKR-03', 'SKR-04'],
            prerequisiteNodeSlugs: ['corner-tag-skips'],
          },
          {
            slug: 'x-out-skips',
            order: 4,
            title: 'X-Out Skips',
            subtitle: 'Second rotation X-outs — find the slow shooter.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['SKR-05'],
            prerequisiteNodeSlugs: ['pnr-post-skips'],
          },
        ],
        bossChallenge: {
          slug: 'wing-skip-boss',
          title: 'Boss — Skip Reader',
          subtitle: '5 reps. No hints. 80% to pass.',
          scenarioIds: [...SKR_IDS],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
          hideDecoderPill: true,
        },
      },
    ],
    unlockCriteria: { pathwaysMastered: ['complete-iq-foundation', 'closeout-killer'] },
    passCriteria: {},
    estimatedMinutes: 90,
    recommendedFor: ['attacker', 'connector'],
    targetArchetype: 'attacker',
    comingSoon: true,
    parentSummary:
      'Player handles modern wing responsibilities: read the catch, react quickly, and choose between shoot, drive, and the next pass.',
    coachSummary:
      'The modern wing role demands triple-decision speed on every catch. This Pathway turns catch-and-freeze into catch-and-act.',
    basketballProblem: 'Player has tools but freezes on the catch.',
    difficultyRange: [3, 5],
  },
  {
    slug: 'big-man-connector',
    title: 'Big Man Connector',
    subtitle: 'A big who passes opens every action on the floor.',
    description:
      'Find the helper who left. Catch on the elbow and choose: shoot, drive, or kick. Punish the double instead of forcing through it.',
    accentToken: 'info',
    decoderTags: ['SKIP_THE_ROTATION', 'ADVANTAGE_OR_RESET'],
    chapters: [
      {
        slug: 'find-the-helper',
        order: 1,
        title: 'Find the Helper',
        subtitle: 'When two defenders come, somebody left a man.',
        basketballCue:
          'A weak-side defender stunts or fully rotates into the ball; the shooter he left is open.',
        decoderTag: 'SKIP_THE_ROTATION',
        decoderTags: ['SKIP_THE_ROTATION'],
        goal: 'Read the help-side rotation and pass to the abandoned shooter rather than forcing the finish.',
        parentSummary:
          'Player learns to see the defender who committed to help, name the shooter he left, and deliver the skip pass before the recovery.',
        coachSummary:
          'Bigs who catch and force are easy to guard. This chapter teaches the read that turns a paint catch into a kick-out three.',
        passCriteria: CHAPTER_PASS,
        masteryCriteria: CHAPTER_MASTERY,
        skillNodes: [
          {
            slug: 'learn-the-cue',
            order: 1,
            title: 'Learn the Cue',
            subtitle: 'Read the lesson, then take one easy rep.',
            kind: 'learn-cue',
            trainingMode: 'learn-the-cue',
            academyLessonSlug: 'skip-the-rotation',
            scenarioIds: ['SKR-01'],
          },
          {
            slug: 'corner-help-leaves',
            order: 2,
            title: 'Corner Help Leaves',
            subtitle: 'Tagger steps up; corner shooter is alone.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['SKR-01', 'SKR-02'],
            prerequisiteNodeSlugs: ['learn-the-cue'],
          },
          {
            slug: 'wing-double-leaves',
            order: 3,
            title: 'Wing Double Leaves',
            subtitle: 'Post double leaves the wing.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['SKR-03'],
            prerequisiteNodeSlugs: ['corner-help-leaves'],
          },
        ],
        bossChallenge: {
          slug: 'helper-finder',
          title: 'Boss — Helper Finder',
          subtitle: '5 reps. No hints. 80% to pass.',
          scenarioIds: [...SKR_IDS],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
          hideDecoderPill: true,
        },
      },
      {
        slug: 'catch-and-decide',
        order: 2,
        title: 'Catch and Decide',
        subtitle: 'Read the closeout before you put it on the floor.',
        basketballCue:
          'Help defender flying out at the catch — read his feet, balance, and cushion before you dribble.',
        decoderTag: 'ADVANTAGE_OR_RESET',
        decoderTags: ['ADVANTAGE_OR_RESET'],
        goal: 'On the elbow / short-roll catch, choose between shoot, drive, and kick based on the closing defender, not a habit.',
        parentSummary:
          'Player handles catches in the middle of the floor without defaulting to a single move; reads the defender first.',
        coachSummary:
          'High-post and short-roll catches force a three-way choice. This chapter trains the closeout read that picks the right one.',
        passCriteria: CHAPTER_PASS,
        masteryCriteria: CHAPTER_MASTERY,
        skillNodes: [
          {
            slug: 'learn-the-cue',
            order: 1,
            title: 'Learn the Cue',
            subtitle: 'Read the lesson, then take one easy rep.',
            kind: 'learn-cue',
            trainingMode: 'learn-the-cue',
            academyLessonSlug: 'advantage-or-reset',
            scenarioIds: ['AOR-01'],
          },
          {
            slug: 'flat-feet-go',
            order: 2,
            title: 'Flat Feet Means Go',
            subtitle: 'Drive past the closeout when his feet stop.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['AOR-01', 'AOR-02'],
            prerequisiteNodeSlugs: ['learn-the-cue'],
          },
          {
            slug: 'square-reset',
            order: 3,
            title: 'Square Stance, Reset',
            subtitle: 'Balanced defender; swing the ball.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['AOR-03'],
            prerequisiteNodeSlugs: ['flat-feet-go'],
          },
          {
            slug: 'long-vs-short-close',
            order: 4,
            title: 'Long vs Short Close',
            subtitle: 'Catch-and-shoot vs catch-and-attack.',
            kind: 'scenario-set',
            trainingMode: 'freeze-frame-read',
            scenarioIds: ['AOR-04', 'AOR-05'],
            prerequisiteNodeSlugs: ['square-reset'],
          },
        ],
        bossChallenge: {
          slug: 'catch-decider',
          title: 'Boss — Big Decider',
          subtitle: '5 reps. No hints. 80% to pass.',
          scenarioIds: [...AOR_IDS],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 5 },
          hideDecoderPill: true,
        },
      },
      {
        slug: 'connector-mix',
        order: 3,
        title: 'Connector Mix',
        subtitle: 'Now read the play, not the decoder.',
        basketballCue:
          'Help rotations and closeouts, mixed and unlabeled. The big has to name the cue before answering.',
        decoderTag: null,
        decoderTags: ['SKIP_THE_ROTATION', 'ADVANTAGE_OR_RESET'],
        goal: 'Make game-like connector reads (skip vs catch-and-decide) without being told which decoder to use.',
        parentSummary:
          'Player demonstrates cross-decoder cue identification across the two reads bigs face most: the help rotation and the closeout.',
        coachSummary:
          'Player will self-identify whether the rep is a rotation read or a catch read, then execute the right answer without a decoder pill.',
        passCriteria: { minBest: 6, minDecoderAccuracy: 0.7 },
        masteryCriteria: { minBest: 8, minDecoderAccuracy: 0.8, minDecoderAttempts: 5 },
        skillNodes: [
          {
            slug: 'mixed-warmup',
            order: 1,
            title: 'Mixed Reads — Warmup',
            subtitle: '5 randomized reps. Decoder pill hidden.',
            kind: 'mixed',
            trainingMode: 'mixed-reads',
            scenarioIds: [...SKR_IDS, ...AOR_IDS],
          },
          {
            slug: 'mixed-pressure',
            order: 2,
            title: 'Mixed Reads — Pressure',
            subtitle: '5 reps with a tighter freeze window.',
            kind: 'mixed',
            trainingMode: 'pressure-test',
            scenarioIds: [...SKR_IDS, ...AOR_IDS],
            prerequisiteNodeSlugs: ['mixed-warmup'],
          },
        ],
        bossChallenge: {
          slug: 'connector-boss',
          title: 'Pathway Boss — Connector',
          subtitle: '10 mixed reps. 80% to pass.',
          scenarioIds: [...SKR_IDS, ...AOR_IDS],
          passCriteria: { bossBestRatio: 0.8, bossMinAttempts: 10 },
          hideDecoderPill: true,
        },
      },
    ],
    unlockCriteria: { pathwaysMastered: ['complete-iq-foundation'] },
    passCriteria: { minBest: 14, minDecoderAccuracy: 0.7 },
    estimatedMinutes: 75,
    recommendedFor: ['connector'],
    targetArchetype: 'connector',
    comingSoon: false,
    parentSummary:
      'Player makes correct passing reads from the high post and short roll, finding the open shooter behind a help rotation.',
    coachSummary:
      'High-IQ bigs unlock four-out spacing. This Pathway trains the elbow and short-roll reads that turn a catch into an advantage.',
    basketballProblem:
      'Bigs who catch and either force a contested finish or pass into help.',
    difficultyRange: [3, 5],
  },
  {
    slug: 'pressure-and-speed',
    title: 'Pressure & Speed Mode',
    subtitle: 'Read it fast — game speed, no hints.',
    description: '4-second reads. No-hint reps. Rapid-fire mixed reads.',
    accentToken: 'heat',
    decoderTags: [
      'BACKDOOR_WINDOW',
      'EMPTY_SPACE_CUT',
      'ADVANTAGE_OR_RESET',
      'SKIP_THE_ROTATION',
    ],
    chapters: [],
    unlockCriteria: {},
    passCriteria: {},
    estimatedMinutes: 60,
    recommendedFor: ['floor-general', 'attacker'],
    targetArchetype: 'floor-general',
    comingSoon: true,
    parentSummary:
      'Player can recognize and execute the correct read at varsity / AAU game speed without pre-freeze prompts.',
    coachSummary:
      'Slow correct equals garbage time. This Pathway shrinks the read window until decisions are automatic at game speed.',
    basketballProblem: 'Player can read it slow but can’t read it fast.',
    difficultyRange: [4, 5],
  },
  {
    slug: 'advanced-game-reads',
    title: 'Advanced Game Reads',
    subtitle: 'Cross-decoder, cue-identification, real-game mix.',
    description: 'Cue identification. Multi-step reads. Decoder mix as it appears in real basketball.',
    accentToken: 'iq',
    decoderTags: [
      'BACKDOOR_WINDOW',
      'EMPTY_SPACE_CUT',
      'ADVANTAGE_OR_RESET',
      'SKIP_THE_ROTATION',
    ],
    chapters: [],
    unlockCriteria: {},
    passCriteria: {},
    estimatedMinutes: 60,
    recommendedFor: ['floor-general'],
    targetArchetype: 'floor-general',
    comingSoon: true,
    parentSummary:
      'Player demonstrates cross-decoder cue identification and multi-step decision-making — the threshold between trainee and decoder.',
    coachSummary:
      'Real basketball doesn’t tell you which read it is. This Pathway forces the player to identify the cue before they execute.',
    basketballProblem:
      'Real basketball doesn’t tell you which read it is — you have to identify the cue.',
    difficultyRange: [4, 5],
  },
]

export const PATHWAYS: readonly PathwayConfig[] = [FOUNDATION, ...COMING_SOON]

/** Slug of the Foundation Pathway. Surfaced as a constant so the home
 * page CTA and the recommendation logic don't have to hand-roll the
 * string. */
export const FOUNDATION_SLUG = 'complete-iq-foundation'
